'use client'

import { useEffect, useState } from 'react'
import { Globe } from 'lucide-react'

export default function LanguageSwitcher() {
  const [isReady, setIsReady] = useState(false)

  useEffect(() => {
    // 1. Check if script is already present to prevent duplicates
    if (document.getElementById('google-translate-script')) {
      return
    }

    // 2. Define the callback function globally BEFORE loading script
    // @ts-ignore
    window.googleTranslateElementInit = () => {
      // @ts-ignore
      if (window.google && window.google.translate) {
        // @ts-ignore
        new window.google.translate.TranslateElement(
          {
            pageLanguage: 'en',
            // Limit to South African languages + Major International Trade languages
            includedLanguages: 'en,af,zu,xh,fr,pt,es,de,zh-CN,hi,ar,ru,ja', 
            // @ts-ignore
            layout: window.google.translate.TranslateElement.InlineLayout.SIMPLE,
            autoDisplay: false,
          },
          'google_translate_element'
        )
        setIsReady(true)
      }
    }

    // 3. Manually create and append the script tag
    // This ensures correct execution order: Callback -> Script Load -> Callback Trigger
    const script = document.createElement('script')
    script.id = 'google-translate-script'
    script.src = '//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit'
    script.async = true
    document.body.appendChild(script)

    return () => {
      // Optional: Cleanup if needed, but usually we want to keep the script
    }
  }, [])

  return (
    <div className="flex items-center gap-2 border border-slate-200 rounded-md px-2 py-1 bg-white hover:bg-slate-50 transition-colors relative z-50 h-9">
      {/* Icon */}
      <Globe className="h-4 w-4 text-slate-500 flex-shrink-0" />
      
      {/* Widget Container */}
      <div 
        id="google_translate_element" 
        className="flex items-center justify-center text-xs text-slate-600 overflow-hidden"
      >
         {/* Only show loading if Google hasn't taken over yet */}
         {!isReady && <span className="px-1">Loading...</span>}
      </div>

      {/* Styles to customize the Google Widget */}
      <style jsx global>{`
        /* 1. Hide Top Frame & "Translated by" Banner */
        .goog-te-banner-frame {
          display: none !important;
        }
        .skiptranslate > iframe {
            display: none !important; /* Hides the top banner iframe */
        }
        body {
          top: 0px !important;
        }
        
        /* 2. Container Styling - Concise Box */
        #google_translate_element {
          display: inline-block !important;
          height: 100%;
          vertical-align: middle;
        }

        /* 3. The Main Button generated by Google */
        .goog-te-gadget-simple {
          background-color: transparent !important;
          border: none !important;
          padding: 0 !important;
          margin: 0 !important;
          font-size: 13px !important;
          font-family: inherit !important;
          display: flex !important;
          align-items: center !important;
          cursor: pointer !important;
          height: 100%;
        }

        /* 4. Text inside the button */
        .goog-te-menu-value {
          color: #475569 !important; /* slate-600 */
          display: flex !important;
          align-items: center !important;
          max-width: 100px; /* Force concise width */
          overflow: hidden;
          white-space: nowrap;
        }
        
        .goog-te-menu-value span {
          color: #475569 !important;
          border-left: none !important;
          text-decoration: none !important;
          font-weight: 500 !important;
          overflow: hidden;
          text-overflow: ellipsis;
        }
        
        /* Hide the awkward vertical separator Google adds */
        .goog-te-menu-value span:nth-child(even) {
            display: none !important;
        }

        /* 5. Cleanup Icons & Branding */
        .goog-te-gadget-icon {
          display: none !important;
        }
        
        /* 6. Hide "Powered by Google" text */
        .goog-te-gadget {
          color: transparent !important;
          font-size: 0 !important;
        }
        .goog-te-gadget > span {
            display: none !important;
        }
        .goog-te-gadget > div {
            display: inline-block !important;
        }

        /* 7. Dropdown Menu Styling */
        .goog-te-menu-frame {
          box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1) !important;
          border: 1px solid #e2e8f0 !important;
          border-radius: 0.5rem !important;
          z-index: 2147483647 !important;
          position: absolute !important;
        }
      `}</style>
    </div>
  )
}